"""initial migration for comments replies

Revision ID: b422438a7776
Revises: 
Create Date: 2025-10-17 11:10:27.754460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b422438a7776'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shoe_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))

        batch_op.create_foreign_key('fk_comments_user_id', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_comments_shoe_id', 'shoes', ['shoe_id'], ['id'])
        batch_op.create_foreign_key('fk_comments_parent_id', 'comments', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('shoe_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
